<?php
include 'dbconnect.php';
$key_id = "rzp_test_GcTeVxxExzh3aL";
$sql = "SELECT * FROM orginzation  WHERE id='1'";
$result = mysqli_query($conn,$sql) or die("SQL Query Failed.");
$row = mysqli_fetch_assoc($result);
$oname = $row["orginzationname"];
$cart = unserialize($_COOKIE['CartProduct']);
$sub_total = $cart['sub_total'];
?>
<style type="text/css">
    .razorpay-payment-button{
        display: none;
    }
</style>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<form action="order.php" method="POST">
    <?php
    if(isset($_POST['name']) && isset($_POST['address']) && isset($_POST['state']) && isset($_POST['city']) && isset($_POST['pincode']) && isset($_POST['email']) && isset($_POST['phone']) && isset($_COOKIE['CartProduct'])){
       ?>
       <script
       src="https://checkout.razorpay.com/v1/checkout.js"
       data-key="<?php echo $key_id; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
       data-amount="<?php echo $sub_total * 100;?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
       data-currency="INR"//You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
       data-id="<?php echo 'OID'.RAND(10,100).'END'; ?>"//Replace with the order_id generated by you in the backend.
       data-buttontext="Pay Now"
       data-name="<?php echo $oname; ?>"
       data-description="Pay Securely With Us"
       data-image="https://www.pngfind.com/pngs/m/162-1628039_ecommerce-benefits-e-commerce-logo-transparent-hd-png.png"
       data-prefill.name="<?php echo $_POST['name'];?>"
       data-prefill.email="<?php echo $_POST['email'];?>"
       data-prefill.contact="<?php echo $_POST['phone'];?>"
       data-theme.color="#FF8C00"
       ></script>
       <input type="hidden" custom="Hidden Element"  name="hidden">
       <input type="hidden" custom="Hidden Element" value="<?php echo $_POST['name']?>" name="user_name">
       <input type="hidden" custom="Hidden Element" value="<?php echo $_POST['address']?>" name="user_address">
       <input type="hidden" custom="Hidden Element" value="<?php echo $_POST['state']?>" name="user_state">
       <input type="hidden" custom="Hidden Element" value="<?php echo $_POST['city']?>" name="user_city">
       <input type="hidden" custom="Hidden Element" value="<?php echo $_POST['pincode']?>" name="user_pincode">
       <input type="hidden" custom="Hidden Element" value="<?php echo $_POST['email']?>" name="user_email">
       <input type="hidden" custom="Hidden Element" value="<?php echo $_POST['phone']?>" name="user_phone">
       <?php
   }else{
    echo "<script>window.open('checkout.php','_self')</script>";
}
?>    
</form>
<script type="text/javascript">
    $(document).ready(function(){
        $(".razorpay-payment-button").click();
    });
</script>
